server:
  port: 8082

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://mysql:3306/h_user_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USER:app}
    password: ${DB_PASS:app_pass}
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.harry.user.model.po
  configuration:
    map-underscore-to-camel-case: true

eureka:
  client:
    service-url:
      defaultZone: http://registry-service:8761/eureka/
