server:
  port: 8082

spring:
  application:
    name: user-service
  spring:
    datasource:
      url: jdbc:mysql://mysql:3306/h_user_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      username: ${DB_USER:app}
      password: ${DB_PASS:app_pass}
      driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://registry-service:8761/eureka/
